### ISSUE TITLE
Errors at build time (clickable and ModalBottomSheet functions)

### ISSUE THREAD

**Issue by santyas** [Chaintech-Network/compose_multiplatform_date_time_picker#7]
Hello!
Thank you for your help!

When I choose rebuild or make project, I get these errors in the build console tasks:

> Task :composeApp:linkDebugFrameworkIosX64
> Task :composeApp:linkDebugFrameworkIosSimulatorArm64
> Task :composeApp:linkDebugFrameworkIosArm64
> Task :composeApp:linkReleaseFrameworkIosSimulatorArm64
> Task :composeApp:linkReleaseFrameworkIosX64
and
> Task :composeApp:linkReleaseFrameworkIosArm64

`<network.chaintech:kmp-date-time-picker> @ /Users/bcsn-savanv/StudioProjects/libs/DateTimePicker/DateTimePickerLibWithDemo/kmp-date-time-picker/src/commonMain/kotlin/network/chaintech/kmp_date_time_picker/ui/datepicker/WheelDatePickerBottomSheet.kt:54:9: Function 'ModalBottomSheet' can not be called: No function found for symbol 'androidx.compose.material3/ModalBottomSheet|ModalBottomSheet(kotlin.Function0<kotlin.Unit>;androidx.compose.ui.Modifier?;androidx.compose.material3.SheetState?;androidx.compose.ui.unit.Dp;androidx.compose.ui.graphics.Shape?;androidx.compose.ui.graphics.Color;androidx.compose.ui.graphics.Color;androidx.compose.ui.unit.Dp;androidx.compose.ui.graphics.Color;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>?;androidx.compose.foundation.layout.WindowInsets?;androidx.compose.material3.ModalBottomSheetProperties?;kotlin.Function3<androidx.compose.foundation.layout.ColumnScope,androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int;kotlin.Int;kotlin.Int){}[0]'`

`<network.chaintech:kmp-date-time-picker> @ /Users/bcsn-savanv/StudioProjects/libs/DateTimePicker/DateTimePickerLibWithDemo/kmp-date-time-picker/src/commonMain/kotlin/network/chaintech/kmp_date_time_picker/ui/datetimepicker/WheelDateTimePickerDialog.kt:115:10: Function 'clickable' can not be called: No function found for symbol 'androidx.compose.foundation/clickable|clickable@androidx.compose.ui.Modifier(androidx.compose.foundation.interaction.MutableInteractionSource;androidx.compose.foundation.Indication?;kotlin.Boolean;kotlin.String?;androidx.compose.ui.semantics.Role?;kotlin.Function0<kotlin.Unit>){}[0]'`

`<network.chaintech:kmp-date-time-picker> @ /Users/bcsn-savanv/StudioProjects/libs/DateTimePicker/DateTimePickerLibWithDemo/kmp-date-time-picker/src/commonMain/kotlin/network/chaintech/kmp_date_time_picker/ui/timepicker/WheelTimePickerBottomSheet.kt:62:9: Function 'ModalBottomSheet' can not be called: No function found for symbol 'androidx.compose.material3/ModalBottomSheet|ModalBottomSheet(kotlin.Function0<kotlin.Unit>;androidx.compose.ui.Modifier?;androidx.compose.material3.SheetState?;androidx.compose.ui.unit.Dp;androidx.compose.ui.graphics.Shape?;androidx.compose.ui.graphics.Color;androidx.compose.ui.graphics.Color;androidx.compose.ui.unit.Dp;androidx.compose.ui.graphics.Color;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>?;androidx.compose.foundation.layout.WindowInsets?;androidx.compose.material3.ModalBottomSheetProperties?;kotlin.Function3<androidx.compose.foundation.layout.ColumnScope,androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int;kotlin.Int;kotlin.Int){}[0]'`

`<network.chaintech:kmp-date-time-picker> @ /Users/bcsn-savanv/StudioProjects/libs/DateTimePicker/DateTimePickerLibWithDemo/kmp-date-time-picker/src/commonMain/kotlin/network/chaintech/kmp_date_time_picker/ui/timepicker/WheelTimePickerBottomSheet.kt:98:10: Function 'clickable' can not be called: No function found for symbol 'androidx.compose.foundation/clickable|clickable@androidx.compose.ui.Modifier(androidx.compose.foundation.interaction.MutableInteractionSource;androidx.compose.foundation.Indication?;kotlin.Boolean;kotlin.String?;androidx.compose.ui.semantics.Role?;kotlin.Function0<kotlin.Unit>){}[0]'`

`<network.chaintech:kmp-date-time-picker> @ /Users/bcsn-savanv/StudioProjects/libs/DateTimePicker/DateTimePickerLibWithDemo/kmp-date-time-picker/src/commonMain/kotlin/network/chaintech/kmp_date_time_picker/utils/DateCommonUtils.kt:213:10: Function 'clickable' can not be called: No function found for symbol 'androidx.compose.foundation/clickable|clickable@androidx.compose.ui.Modifier(androidx.compose.foundation.interaction.MutableInteractionSource;androidx.compose.foundation.Indication?;kotlin.Boolean;kotlin.String?;androidx.compose.ui.semantics.Role?;kotlin.Function0<kotlin.Unit>){}[0]'`

`<missing declarations>: No function found for symbol 'androidx.compose.material3/ModalBottomSheet|ModalBottomSheet(kotlin.Function0<kotlin.Unit>;androidx.compose.ui.Modifier?;androidx.compose.material3.SheetState?;androidx.compose.ui.unit.Dp;androidx.compose.ui.graphics.Shape?;androidx.compose.ui.graphics.Color;androidx.compose.ui.graphics.Color;androidx.compose.ui.unit.Dp;androidx.compose.ui.graphics.Color;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>?;androidx.compose.foundation.layout.WindowInsets?;androidx.compose.material3.ModalBottomSheetProperties?;kotlin.Function3<androidx.compose.foundation.layout.ColumnScope,androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int;kotlin.Int;kotlin.Int){}[0]'`

`<missing declarations>: No function found for symbol 'androidx.compose.foundation.selection/toggleable|toggleable@androidx.compose.ui.Modifier(kotlin.Boolean;androidx.compose.foundation.interaction.MutableInteractionSource;androidx.compose.foundation.Indication?;kotlin.Boolean;androidx.compose.ui.semantics.Role?;kotlin.Function1<kotlin.Boolean,kotlin.Unit>){}[0]'`

`<missing declarations>: No function found for symbol 'androidx.compose.foundation/clickable|clickable@androidx.compose.ui.Modifier(androidx.compose.foundation.interaction.MutableInteractionSource;androidx.compose.foundation.Indication?;kotlin.Boolean;kotlin.String?;androidx.compose.ui.semantics.Role?;kotlin.Function0<kotlin.Unit>){}[0]'`

I'm using `network.chaintech:kmp-date-time-picker:1.0.3` because on .4 or .5 it crashs.
Project created by jetbrains wizard.

My gradle:
https://gist.github.com/santyas/5a79f1d997a571c3ebfb8d0354c8ffee

**Comment by mobiletoly** [comment]
I doubt it has anything to do with this specific library. I had a similar issue recently with something else. In my case it was because I was using compose 1.7.3, but I forgot to bump up compose plugin "org.jetbrains.compose" version. Once I updated:

[versions]
compose-plugin = "1.7.0-rc01"

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }

it solved the issue

**Comment by santyas** [comment]
@mobiletoly I'm using 1.6.11 of compose-plugin. Cannot upgrade to 1.7.0 bc my app crashes and idk why at the moment.

**Comment by santyas** [comment]
Solved. I had to update some dependency versions.
